# Generated by Django 3.2.5 on 2021-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
                ('mail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
