# Generated by Django 3.2.5 on 2021-08-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210827_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_type',
        ),
    ]
